# Lecture 1

In [9]:
import numpy as np

v1 = np.array([8,4,7])
v2 = np.array([2,8,1])
v3 = np.array([3,1,1])
v4 = np.array([9,7,4]) 

stacked_vectors = np.vstack((v1, v2, v3, v4))
X               = np.column_stack([v1, v2, v3, v4])
n               = len(stacked_vectors)

# Calculate the mean along axis 0 (down the columns)
mean_vector = np.mean(stacked_vectors, axis=0)

#covariance_matrix = np.cov(stacked_vectors)

n = X.shape[1]
S = (X @ X.T) / n - x_bar @ x_bar.T

print("Stacked vectors:")
print(stacked_vectors)
print("\nMean of corresponding elements:")
print(mean_vector)

#print("Sample Covariance Matrix:\n", covariance_matrix)
print("Matriz de covarianza S =\n", S)
print("S11 =", S[0,0])
print("S21 =", S[1,0])
print("S32 =", S[2,1])


Stacked vectors:
[[8 4 7]
 [2 8 1]
 [3 1 1]
 [9 7 4]]

Mean of corresponding elements:
[5.5  5.   3.25]
Matriz de covarianza S =
 [[9.25   1.     6.375 ]
 [1.     7.5    0.    ]
 [6.375  0.     6.1875]]
S11 = 9.25
S21 = 1.0
S32 = 0.0


In [6]:
import numpy as np

# Define the data vectors as a matrix X, where each column is a data point
# The problem gives a d x n matrix X where d=3 and n=4
X = np.array([
    [8, 2, 3, 9],
    [4, 8, 1, 7],
    [7, 1, 1, 4]
])

# Get dimensions of the data matrix
d, n = X.shape

# 1. Calculate the empirical mean vector (x_bar)
# The sum of columns divided by the number of columns
x_bar = np.mean(X, axis=1, keepdims=True)

# 2. Subtract the mean from each column of X to get the centered matrix Z
Z = X - x_bar

# 3. Calculate the empirical covariance matrix S
# S = (1/n) * Z * Z.T
S = (1/n) * np.dot(Z, Z.T)

# Print the final results
print("The empirical mean vector (x_bar) is:")
print(x_bar)
print("\nThe empirical covariance matrix (S) is:")
print(S)

# Print the specific entries requested in the problem, rounded to 3 decimal places
print("\nRequested entries:")
print(f"S_11 = {S[0, 0]:.3f}")  # S_11 is S[0,0] in Python (0-indexed)
print(f"S_21 = {S[1, 0]:.3f}")  # S_21 is S[1,0]
print(f"S_32 = {S[2, 1]:.3f}")  # S_32 is S[2,1]

The empirical mean vector (x_bar) is:
[[5.5 ]
 [5.  ]
 [3.25]]

The empirical covariance matrix (S) is:
[[9.25   1.     6.375 ]
 [1.     7.5    0.    ]
 [6.375  0.     6.1875]]

Requested entries:
S_11 = 9.250
S_21 = 1.000
S_32 = 0.000


In [5]:
I = np.array([[1,0,0],[0,1,0], [0,0,1] ])
one = np.array([[1,1,1],[1,1,1], [1,1,1] ])
n = 3
x = np.array([2, -1, -2])

In [25]:
H = I-one/n
H

array([[ 0.66666667, -0.33333333, -0.33333333],
       [-0.33333333,  0.66666667, -0.33333333],
       [-0.33333333, -0.33333333,  0.66666667]])

In [26]:
H @ x

array([ 2.33333333, -0.66666667, -1.66666667])

In [ ]:
H @ H @ x

array([ 2.33333333, -0.66666667, -1.66666667])

In [ ]:
import numpy as np

def proyection(vector_proyectado, vector_receptor_de_proyeccion):
    v1 = vector_proyectado
    u1 = vector_receptor_de_proyeccion
    if not np.isclose(np.linalg.norm(u1), 1.0):
        print("El vector u1 no es unitario. Normalizándolo...")
        u1 = u1 / np.linalg.norm(u1)

    # 2. Calcular la proyeccion
    # La fórmula es: (v1 . u1) * u1
    # np.dot(v1, u1) calcula el producto punto
    proyeccion_v1_en_u1 = np.dot(v1, u1) * u1
    return proyeccion_v1_en_u1

# CASO EJEMPLO
# Definir los vectores
v1 = np.array([2, 3])
u1 = np.array([1, 0]) # Este es un vector unitario de ejemplo


# Imprimir el resultado
print(f"El vector v1 es: {v1}")
print(f"El vector unitario u1 es: {u1}")
print(f"La proyección de v1 en u1 es: {proyection(v1,u1)}")

El vector v1 es: [2 3]
El vector unitario u1 es: [1 0]
La proyección de v1 en u1 es: [2 0]


In [3]:
x1 = np.array([1,2]) 
x2 = np.array([3,4])
x3 = np.array([-1,0])

u = np.array([1,2])

print(proyection(x1, u))
print(proyection(x2, u))
print(proyection(x3, u))


El vector u1 no es unitario. Normalizándolo...
[1. 2.]
El vector u1 no es unitario. Normalizándolo...
[2.2 4.4]
El vector u1 no es unitario. Normalizándolo...
[-0.2 -0.4]


## Parte 7

In [ ]:
from math import sqrt

u = u/sqrt(5)
print(np.dot(u,x1))
print(np.dot(u,x2))
print(np.dot(u,x3))

2.23606797749979
4.919349550499537
-0.4472135954999579


In [21]:
print(np.var([np.dot(u,x1), np.dot(u,x2), np.dot(u,x3)]))


4.8


In [39]:
I = np.eye(3)
one = np.ones((3,1))
X = np.vstack([x1, x2, x3])
S = 1/3*X.T @ (I-1/3* one @ one.T) @ X
S
result = u.T @ S @ u
print(f'resultado : {result}')

resultado : 4.8


## Parte 9

In [42]:
X = np.array([[0,1], [0,-1]])
n = 2

# SAMPLE COVARIANCE MATRIX

S = 1/n * X.T @ X
S 

array([[0., 0.],
       [0., 1.]])

## Parte 12

In [51]:
v1 = np.array([0,2])
v2 = np.array([0,-2])
v3 = np.array([1,1])
v4 = np.array([-1,-1])
X = np.vstack([v1,v2,v3,v4])
n = X.shape[0]


S = 1/n * X.T @ X
print('SAMPLE COVARIANCE MATRIX')
S 


SAMPLE COVARIANCE MATRIX


array([[0.5, 0.5],
       [0.5, 2.5]])

In [52]:
eigvals, eigvecs = np.linalg.eig(S)

print("Valores propios:", eigvals)
print("Vectores propios:\n", eigvecs)

Valores propios: [0.38196601 2.61803399]
Vectores propios:
 [[-0.97324899 -0.22975292]
 [ 0.22975292 -0.97324899]]


In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(S)

# PCA requiere que los valores propios estén ordenados de mayor a menor.
# np.argsort devuelve los índices que ordenarían el array.
# [::-1] invierte el orden para que sea de mayor a menor.
idx = eigenvalues.argsort()[::-1]

# Ordenar valores propios y vectores propios
lambda_sorted = eigenvalues[idx]
v_sorted = eigenvectors[:, idx]

print("\n--- VALORES PROPIOS (Eigenvalues) ---")
print(f"Lambda 1 (Mayor Varianza): {lambda_sorted[0]:.4f}")
print(f"Lambda 2 (Menor Varianza): {lambda_sorted[1]:.4f}")
# Nota: Los valores propios exactos son (6 + 2*sqrt(5))/3 y (6 - 2*sqrt(5))/3.

print("\n--- VECTORES PROPIOS UNITARIOS (Eigenvectors) ---")
print("Vector Propio 1 (PC1 - Dirección de Máxima Varianza):")
print(v_sorted[:, 0])
print("\nVector Propio 2 (PC2 - Dirección de Mínima Varianza):")
print(v_sorted[:, 1])

--- MATRIZ DE COVARIANZA S ---
[[0.5 0.5]
 [0.5 2.5]]

--- VALORES PROPIOS (Eigenvalues) ---
Lambda 1 (Mayor Varianza): 2.6180
Lambda 2 (Menor Varianza): 0.3820

--- VECTORES PROPIOS UNITARIOS (Eigenvectors) ---
Vector Propio 1 (PC1 - Dirección de Máxima Varianza):
[-0.22975292 -0.97324899]

Vector Propio 2 (PC2 - Dirección de Mínima Varianza):
[-0.97324899  0.22975292]


## Part 16

In [ ]:
x1 = np.array([1,1])
x2 = np.array([1,-1])
x3 = np.array([-1,1])

X = np.vstack([x1,x2,x3])
n = X.shape[0]

B = X @ X.T
B 

array([[ 2,  0,  0],
       [ 0,  2, -2],
       [ 0, -2,  2]])

In [59]:
np.set_printoptions(precision=5)
eigvals, eigvecs = np.linalg.eig(B)

print("Valores propios:", eigvals)
print("Vectores propios:\n", eigvecs)

Valores propios: [4.00000e+00 4.44089e-16 2.00000e+00]
Vectores propios:
 [[ 0.       0.       1.     ]
 [-0.70711  0.70711  0.     ]
 [ 0.70711  0.70711  0.     ]]


In [61]:
vector_prop_1 = np.array([eigvecs[0,0], eigvecs[1,0],eigvecs[2,0]])
valor_prop_1 = eigvals[0]

In [63]:
Y_lambda_1 =  vector_prop_1 * sqrt(valor_prop_1)
Y_lambda_1

array([ 0.     , -1.41421,  1.41421])

## Part 18

In [64]:
import numpy as np
from scipy.optimize import minimize
import math

# --- 1. DEFINICIÓN DE LAS DISTANCIAS ---

# Distancias en Alta Dimensión (X): D_12=1, D_13=1, D_23=sqrt(2)
D_sq_high = np.array([1**2, 1**2, math.sqrt(2)**2])
# D_sq_high = [1, 1, 2]

# --- 2. CÁLCULO DE LA DISTRIBUCIÓN P (Alta Dimensión) ---

def calculate_P(D_sq_high):
    """Calcula la distribución P (conjunta simplificada)."""
    # Numeradores: exp(-D_ij^2)
    numerator_P = np.exp(-D_sq_high)
    # Denominador: Suma de todos los numeradores
    denominator_P = np.sum(numerator_P)
    # P_ij = Numerador / Denominador
    P = numerator_P / denominator_P
    return P[0], P[1], P[2]

p12, p13, p23 = calculate_P(D_sq_high)
P_vector = np.array([p12, p13, p23])

# --- 3. DEFINICIÓN DE LA FUNCIÓN Q (dependiente de 'a') ---

def calculate_Q(a):
    """Calcula la distribución Q (baja dimensión) para una distancia 'a'."""
    # Distancias en Baja Dimensión (Y): d_12=a, d_13=a, d_23=2a
    d_sq_low = np.array([a**2, a**2, (2*a)**2]) 
    
    # Numeradores: exp(-d_ij^2)
    numerator_Q = np.exp(-d_sq_low)
    # Denominador: Suma de todos los numeradores
    denominator_Q = np.sum(numerator_Q)
    
    # Q_ij = Numerador / Denominador
    Q = numerator_Q / denominator_Q
    return Q

# --- 4. FUNCIÓN OBJETIVO: DIVERGENCIA KL(P||Q) ---

def kl_divergence(a, P_vector):
    """Calcula la Divergencia KL(P||Q)."""
    # Restricción: 'a' debe ser positivo
    if a <= 0:
        return np.inf 
        
    Q_vector = calculate_Q(a)
    
    # KL(P||Q) = sum(P_ij * log(P_ij / Q_ij))
    # Usamos log natural (ln) por defecto en numpy
    KL = np.sum(P_vector * np.log(P_vector / Q_vector))
    return KL

# --- 5. RESOLVER NUMÉRICAMENTE LA MINIMIZACIÓN ---

# Usamos 'minimize' para encontrar 'a' que haga la KL mínima
# Punto de partida (guess) para 'a'
a_guess = 0.5

# La función busca el mínimo, que sabemos que debería ser 0.
result = minimize(
    kl_divergence, 
    a_guess, 
    args=(P_vector,), 
    method='L-BFGS-B', 
    bounds=[(1e-6, None)] # 'a' debe ser > 0
)

a_numerical = result.x[0]

# --- 6. RESOLVER ANALÍTICAMENTE (Igualando la relación de probabilidades) ---

# Se requiere resolver: 3*a^2 = 1
a_analytical = 1 / math.sqrt(3)


# --- 7. IMPRIMIR RESULTADOS ---

print(f"--- ANÁLISIS DE KL(P||Q) ---")
print(f"Probabilidades P (Alta Dimensión):")
print(f"p12/p13: {p12:.6f}, p23: {p23:.6f}")
print("-" * 30)
print(f"VALOR MÍNIMO DE 'a' (Analítico): {a_analytical:.6f}")
print(f"VALOR MÍNIMO DE 'a' (Numérico, SciPy): {a_numerical:.6f}")
print(f"KL Mínima Encontrada: {result.fun:.2e}")
print("-" * 30)

# Comprobación de P = Q en el valor mínimo de 'a'
Q_at_min_a = calculate_Q(a_analytical)
print(f"Probabilidades Q con a={a_analytical:.6f}:")
print(f"q12/q13: {Q_at_min_a[0]:.6f}, q23: {Q_at_min_a[2]:.6f}")

print(f"\nVerificación: ¿P == Q? {np.allclose(P_vector, Q_at_min_a)}")

--- ANÁLISIS DE KL(P||Q) ---
Probabilidades P (Alta Dimensión):
p12/p13: 0.422319, p23: 0.155362
------------------------------
VALOR MÍNIMO DE 'a' (Analítico): 0.577350
VALOR MÍNIMO DE 'a' (Numérico, SciPy): 0.000001
KL Mínima Encontrada: 2.44e-01
------------------------------
Probabilidades Q con a=0.577350:
q12/q13: 0.422319, q23: 0.155362

Verificación: ¿P == Q? True


In [66]:
import numpy as np
from scipy.optimize import root_scalar, fsolve

# --- 1. Calcular P12 (Probabilidad de Alta Dimensión) ---

# Distancias al cuadrado en Alta Dimensión (X)
D_sq_12 = 1
D_sq_23 = 2 # sqrt(2)^2

# Numeradores no normalizados (Gaussianos simplificados)
num_12_P = np.exp(-D_sq_12)
num_23_P = np.exp(-D_sq_23)

# Denominador (Suma de los 3 pares únicos)
denom_P = num_12_P + num_12_P + num_23_P # p12, p13, p23

# Probabilidad P12 (es constante)
P12 = num_12_P / denom_P
print(f"Probabilidad P12 (High D): {P12:.6f}")


# --- 2. Definir la función para Q12(a) (Probabilidad de Baja Dimensión) ---

def Q12(a):
    """
    Calcula la probabilidad q12 en baja dimensión usando el kernel t de Student (df=1).
    Distancias: d_12=a, d_13=a, d_23=2a
    Kernel: (1 + d^2)^-1
    """
    if a <= 0:
        return 0.0 # a debe ser positivo

    # Numerador de q12: (1 + d_12^2)^-1
    num_12_Q = 1 / (1 + a**2)

    # Denominador: Suma de los 3 pares únicos (q12, q13, q23)
    # q12 = q13 = 1 / (1 + a^2)
    # q23 = 1 / (1 + (2a)^2) = 1 / (1 + 4*a^2)
    denom_Q = (2 * num_12_Q) + (1 / (1 + 4 * a**2))

    return num_12_Q / denom_Q


# --- 3. Definir la Ecuación a Resolver: F(a) = Q12(a) - P12 = 0 ---

def equation_to_solve(a):
    """Función para encontrar la raíz (donde la igualdad se cumple)."""
    return Q12(a) - P12


# --- 4. Resolver Numéricamente ---

# Usaremos fsolve o root_scalar para encontrar la raíz 'a'
# Sabemos que 'a' debe estar entre 0 y 1, por la solución del problema Gaussiano anterior (a ~ 0.577)

# Usamos 'root_scalar' para encontrar la raíz en un intervalo
try:
    solution = root_scalar(equation_to_solve, bracket=[0.01, 1.0], method='brentq')
    a_solution = solution.root
except ValueError:
    # Si brentq falla, probamos con fsolve con un punto inicial
    a_solution = fsolve(equation_to_solve, 0.5)[0]

# --- 5. Imprimir el Resultado ---

print(f"--- SOLUCIÓN NUMÉRICA DE q12 = p12 (t-SNE) ---")
print(f"El valor de a que minimiza KL(P||Q) es: {a_solution:.6f}")

# Comprobación (debería ser casi igual a P12)
Q12_check = Q12(a_solution)
print(f"Verificación: Q12({a_solution:.3f}) = {Q12_check:.6f}")

print("\nLa respuesta solicitada (3 decimales) es:")
print(f"a = {a_solution:.3f}")

Probabilidad P12 (High D): 0.422319
--- SOLUCIÓN NUMÉRICA DE q12 = p12 (t-SNE) ---
El valor de a que minimiza KL(P||Q) es: 1.157846
Verificación: Q12(1.158) = 0.422319

La respuesta solicitada (3 decimales) es:
a = 1.158


# Lecture 2

In [67]:
0.99*0.05/(0.05*0.99+0.95*0.1)

0.34256055363321797

# Lecture 3