# Criminal Networks

# Lecture 1

## Problem 6

In [3]:
import numpy as np
A = np.array([[0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
	[1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
	[1, 1, 0, 0, 0, 1, 0, 1, 1, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
	[1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
	[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
	[0, 0, 0, 0, 1, 0, 1, 0, 1, 0]])

In [13]:
A@A@A@A

array([[19, 14,  7, 21, 12, 11,  2,  7, 11,  5],
       [14, 28,  2, 14,  6, 17,  2, 10, 19, 10],
       [ 7,  2,  4, 10,  7,  2,  1,  1,  2,  2],
       [21, 14, 10, 37, 20, 11,  2,  4,  8, 11],
       [12,  6,  7, 20, 18,  4,  5,  2,  9,  9],
       [11, 17,  2, 11,  4, 12,  1,  7, 11,  4],
       [ 2,  2,  1,  2,  5,  1,  3,  1,  5,  2],
       [ 7, 10,  1,  4,  2,  7,  1,  5,  8,  2],
       [11, 19,  2,  8,  9, 11,  5,  8, 19,  9],
       [ 5, 10,  2, 11,  9,  4,  2,  2,  9, 13]])

In [8]:
A == A.T

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [10]:
A@A@A@A@A

array([[46, 59, 14, 62, 30, 40,  5, 21, 38, 25],
       [59, 36, 28, 88, 57, 28, 10, 14, 30, 27],
       [14, 28,  2, 14,  6, 17,  2, 10, 19, 10],
       [62, 88, 14, 58, 33, 58, 11, 37, 68, 30],
       [30, 57,  6, 33, 24, 32,  9, 20, 47, 32],
       [40, 28, 17, 58, 32, 22,  4, 11, 19, 16],
       [ 5, 10,  2, 11,  9,  4,  2,  2,  9, 13],
       [21, 14, 10, 37, 20, 11,  2,  4,  8, 11],
       [38, 30, 19, 68, 47, 19,  9,  8, 26, 33],
       [25, 27, 10, 30, 32, 16, 13, 11, 33, 20]])

## Problem 7

In [15]:
import numpy as np

# 'release_directed_graph.txt' tiene tus datos
try:
    # np.loadtxt es ideal para archivos simples y limpios
    graph_data = np.loadtxt('release_directed_graph.txt', dtype=int)
    
    # graph_data ahora es un arreglo de NumPy que representa las aristas
    print("Datos cargados exitosamente:")
    print(graph_data)
    
except FileNotFoundError:
    print("Error: Asegúrate de que el archivo 'release_directed_graph.txt' exista.")
except Exception as e:
    print(f"Ocurrió un error al cargar el archivo: {e}")

Datos cargados exitosamente:
[[ 0  3]
 [ 0 10]
 [ 0 12]
 ...
 [99 77]
 [99 81]
 [99 85]]


In [18]:
# Nodes
len(np.unique(graph_data))

100

In [ ]:
# Aristas
len(graph_data)

1030

In [32]:
# Self Cycles?
for arista in graph_data:
    if arista[0] == arista[1]:
        print(arista)
        print('Tiene auto ciclo')
        break


[19 19]
Tiene auto ciclo


In [ ]:
# ¿Tiene loops que no sea self loop? Problemos un llop tal que A -> B y B -> A

In [31]:
graph_data[3][::-1]

array([25,  0])

In [39]:
romper = False
for i in range(len(graph_data)):
    for j in range(len(graph_data)):
        if i != j:
            if graph_data[i][0] == graph_data[j][1] and  graph_data[i][1] == graph_data[j][0]:
                print(f'graph i: {graph_data[i]}')
                print(f'graph j: {graph_data[j]}')
                print('Tiene Cicly Simple')
                romper = True
                break
    if romper == True:
        break


graph i: [ 0 84]
graph j: [84  0]
Tiene Cicly Simple


In [51]:
# ¿Cuanto vale P? 

promedios = []
for nodo in range(len(np.unique(graph_data))):
    #print(f'Leyendo Nodo: {nodo}')
    promedio = 0
    for arista in graph_data:
        if nodo == arista[0]:
            promedio+=1
    promedios.append(promedio)
p = np.average(promedios)

print(f'P value = {p}')

P value = 10.3


In [52]:
# 1. Calcular el número de aristas (e)
num_edges = len(graph_data)

# 2. Calcular el número de nodos (n)
num_nodes = len(np.unique(graph_data.flatten()))

# 3. Calcular la estimación de p
p_mle = num_edges / (num_nodes ** 2)

print(f"Número de aristas (e): {num_edges}")
print(f"Número de nodos (n): {num_nodes}")
print(f"Estimación de p (e/n^2) = {num_edges} / ({num_nodes}^2) = {p_mle}")

# Para obtener el resultado con al menos 5 cifras significativas
print(f"p con 5 cifras significativas: {p_mle:.5f}")

Número de aristas (e): 1030
Número de nodos (n): 100
Estimación de p (e/n^2) = 1030 / (100^2) = 0.103
p con 5 cifras significativas: 0.10300


In [54]:
from scipy.stats import norm
p_null = 0.1
N_total = num_nodes ** 2
print(f"Total de aristas posibles (N_total): {N_total}")

# 1.2. Media Muestral (S_n = p_mle)
S_n = num_edges / N_total
print(f"Media Muestral (S_n): {S_n}")

# 1.3. Media Poblacional bajo H0 (mu_n)
mu_n = p_null
print(f"Media Poblacional (mu_n): {mu_n}")

# 1.4. Desviación Estándar de la Media Muestral (sigma_n)
# Fórmula: sigma_n = sqrt( p_0 * (1 - p_0) / N_total )
sigma_squared = p_null * (1 - p_null)
sigma_n = np.sqrt(sigma_squared / N_total)
print(f"Desviación estándar de la media muestral (sigma_n): {sigma_n:.5f}")


# ----------------------------------------
# --- 2. CÁLCULO DEL ESTADÍSTICO DE PRUEBA Z ---

# Fórmula: Z = | S_n - mu_n | / sigma_n
Z_statistic = np.abs(S_n - mu_n) / sigma_n
print("-" * 40)
print(f"Estadístico Z calculado: {Z_statistic:.3f}")


# ----------------------------------------
# --- 3. CÁLCULO DEL P-VALOR (PRUEBA BILATERAL) ---

# P(Z > Z_statistic) se calcula con la función de supervivencia (sf) de la normal.
# El p-valor bilateral es 2 * P(Z > Z_statistic)
p_value = 2 * norm.sf(Z_statistic)

print("-" * 40)
print(f"P-valor (5 cifras significativas): {p_value:.5f}")

Total de aristas posibles (N_total): 10000
Media Muestral (S_n): 0.103
Media Poblacional (mu_n): 0.1
Desviación estándar de la media muestral (sigma_n): 0.00300
----------------------------------------
Estadístico Z calculado: 1.000
----------------------------------------
P-valor (5 cifras significativas): 0.31731
