# Lecture 1

In [9]:
import numpy as np

v1 = np.array([8,4,7])
v2 = np.array([2,8,1])
v3 = np.array([3,1,1])
v4 = np.array([9,7,4]) 

stacked_vectors = np.vstack((v1, v2, v3, v4))
X               = np.column_stack([v1, v2, v3, v4])
n               = len(stacked_vectors)

# Calculate the mean along axis 0 (down the columns)
mean_vector = np.mean(stacked_vectors, axis=0)

#covariance_matrix = np.cov(stacked_vectors)

n = X.shape[1]
S = (X @ X.T) / n - x_bar @ x_bar.T

print("Stacked vectors:")
print(stacked_vectors)
print("\nMean of corresponding elements:")
print(mean_vector)

#print("Sample Covariance Matrix:\n", covariance_matrix)
print("Matriz de covarianza S =\n", S)
print("S11 =", S[0,0])
print("S21 =", S[1,0])
print("S32 =", S[2,1])


Stacked vectors:
[[8 4 7]
 [2 8 1]
 [3 1 1]
 [9 7 4]]

Mean of corresponding elements:
[5.5  5.   3.25]
Matriz de covarianza S =
 [[9.25   1.     6.375 ]
 [1.     7.5    0.    ]
 [6.375  0.     6.1875]]
S11 = 9.25
S21 = 1.0
S32 = 0.0


In [6]:
import numpy as np

# Define the data vectors as a matrix X, where each column is a data point
# The problem gives a d x n matrix X where d=3 and n=4
X = np.array([
    [8, 2, 3, 9],
    [4, 8, 1, 7],
    [7, 1, 1, 4]
])

# Get dimensions of the data matrix
d, n = X.shape

# 1. Calculate the empirical mean vector (x_bar)
# The sum of columns divided by the number of columns
x_bar = np.mean(X, axis=1, keepdims=True)

# 2. Subtract the mean from each column of X to get the centered matrix Z
Z = X - x_bar

# 3. Calculate the empirical covariance matrix S
# S = (1/n) * Z * Z.T
S = (1/n) * np.dot(Z, Z.T)

# Print the final results
print("The empirical mean vector (x_bar) is:")
print(x_bar)
print("\nThe empirical covariance matrix (S) is:")
print(S)

# Print the specific entries requested in the problem, rounded to 3 decimal places
print("\nRequested entries:")
print(f"S_11 = {S[0, 0]:.3f}")  # S_11 is S[0,0] in Python (0-indexed)
print(f"S_21 = {S[1, 0]:.3f}")  # S_21 is S[1,0]
print(f"S_32 = {S[2, 1]:.3f}")  # S_32 is S[2,1]

The empirical mean vector (x_bar) is:
[[5.5 ]
 [5.  ]
 [3.25]]

The empirical covariance matrix (S) is:
[[9.25   1.     6.375 ]
 [1.     7.5    0.    ]
 [6.375  0.     6.1875]]

Requested entries:
S_11 = 9.250
S_21 = 1.000
S_32 = 0.000


In [23]:
I = np.array([[1,0,0],[0,1,0], [0,0,1] ])
one = np.array([[1,1,1],[1,1,1], [1,1,1] ])
n = 3
x = np.array([2, -1, -2])

In [25]:
H = I-one/n
H

array([[ 0.66666667, -0.33333333, -0.33333333],
       [-0.33333333,  0.66666667, -0.33333333],
       [-0.33333333, -0.33333333,  0.66666667]])

In [26]:
H @ x

array([ 2.33333333, -0.66666667, -1.66666667])

In [32]:
H@H @ x

array([ 2.33333333, -0.66666667, -1.66666667])