# Criminal Networks

# Lecture 1

## Problem 6

In [3]:
import numpy as np
A = np.array([[0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
	[1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
	[1, 1, 0, 0, 0, 1, 0, 1, 1, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
	[1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
	[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
	[0, 0, 0, 0, 1, 0, 1, 0, 1, 0]])

In [13]:
A@A@A@A

array([[19, 14,  7, 21, 12, 11,  2,  7, 11,  5],
       [14, 28,  2, 14,  6, 17,  2, 10, 19, 10],
       [ 7,  2,  4, 10,  7,  2,  1,  1,  2,  2],
       [21, 14, 10, 37, 20, 11,  2,  4,  8, 11],
       [12,  6,  7, 20, 18,  4,  5,  2,  9,  9],
       [11, 17,  2, 11,  4, 12,  1,  7, 11,  4],
       [ 2,  2,  1,  2,  5,  1,  3,  1,  5,  2],
       [ 7, 10,  1,  4,  2,  7,  1,  5,  8,  2],
       [11, 19,  2,  8,  9, 11,  5,  8, 19,  9],
       [ 5, 10,  2, 11,  9,  4,  2,  2,  9, 13]])

In [8]:
A == A.T

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [10]:
A@A@A@A@A

array([[46, 59, 14, 62, 30, 40,  5, 21, 38, 25],
       [59, 36, 28, 88, 57, 28, 10, 14, 30, 27],
       [14, 28,  2, 14,  6, 17,  2, 10, 19, 10],
       [62, 88, 14, 58, 33, 58, 11, 37, 68, 30],
       [30, 57,  6, 33, 24, 32,  9, 20, 47, 32],
       [40, 28, 17, 58, 32, 22,  4, 11, 19, 16],
       [ 5, 10,  2, 11,  9,  4,  2,  2,  9, 13],
       [21, 14, 10, 37, 20, 11,  2,  4,  8, 11],
       [38, 30, 19, 68, 47, 19,  9,  8, 26, 33],
       [25, 27, 10, 30, 32, 16, 13, 11, 33, 20]])

## Problem 7

In [15]:
import numpy as np

# 'release_directed_graph.txt' tiene tus datos
try:
    # np.loadtxt es ideal para archivos simples y limpios
    graph_data = np.loadtxt('release_directed_graph.txt', dtype=int)
    
    # graph_data ahora es un arreglo de NumPy que representa las aristas
    print("Datos cargados exitosamente:")
    print(graph_data)
    
except FileNotFoundError:
    print("Error: Asegúrate de que el archivo 'release_directed_graph.txt' exista.")
except Exception as e:
    print(f"Ocurrió un error al cargar el archivo: {e}")

Datos cargados exitosamente:
[[ 0  3]
 [ 0 10]
 [ 0 12]
 ...
 [99 77]
 [99 81]
 [99 85]]


In [18]:
# Nodes
len(np.unique(graph_data))

100

In [ ]:
# Aristas
len(graph_data)

1030

In [32]:
# Self Cycles?
for arista in graph_data:
    if arista[0] == arista[1]:
        print(arista)
        print('Tiene auto ciclo')
        break


[19 19]
Tiene auto ciclo


In [ ]:
# ¿Tiene loops que no sea self loop? Problemos un llop tal que A -> B y B -> A

In [31]:
graph_data[3][::-1]

array([25,  0])

In [39]:
romper = False
for i in range(len(graph_data)):
    for j in range(len(graph_data)):
        if i != j:
            if graph_data[i][0] == graph_data[j][1] and  graph_data[i][1] == graph_data[j][0]:
                print(f'graph i: {graph_data[i]}')
                print(f'graph j: {graph_data[j]}')
                print('Tiene Cicly Simple')
                romper = True
                break
    if romper == True:
        break


graph i: [ 0 84]
graph j: [84  0]
Tiene Cicly Simple


In [51]:
# ¿Cuanto vale P? 

promedios = []
for nodo in range(len(np.unique(graph_data))):
    #print(f'Leyendo Nodo: {nodo}')
    promedio = 0
    for arista in graph_data:
        if nodo == arista[0]:
            promedio+=1
    promedios.append(promedio)
p = np.average(promedios)

print(f'P value = {p}')

P value = 10.3


In [52]:
# 1. Calcular el número de aristas (e)
num_edges = len(graph_data)

# 2. Calcular el número de nodos (n)
num_nodes = len(np.unique(graph_data.flatten()))

# 3. Calcular la estimación de p
p_mle = num_edges / (num_nodes ** 2)

print(f"Número de aristas (e): {num_edges}")
print(f"Número de nodos (n): {num_nodes}")
print(f"Estimación de p (e/n^2) = {num_edges} / ({num_nodes}^2) = {p_mle}")

# Para obtener el resultado con al menos 5 cifras significativas
print(f"p con 5 cifras significativas: {p_mle:.5f}")

Número de aristas (e): 1030
Número de nodos (n): 100
Estimación de p (e/n^2) = 1030 / (100^2) = 0.103
p con 5 cifras significativas: 0.10300


In [54]:
from scipy.stats import norm
p_null = 0.1
N_total = num_nodes ** 2
print(f"Total de aristas posibles (N_total): {N_total}")

# 1.2. Media Muestral (S_n = p_mle)
S_n = num_edges / N_total
print(f"Media Muestral (S_n): {S_n}")

# 1.3. Media Poblacional bajo H0 (mu_n)
mu_n = p_null
print(f"Media Poblacional (mu_n): {mu_n}")

# 1.4. Desviación Estándar de la Media Muestral (sigma_n)
# Fórmula: sigma_n = sqrt( p_0 * (1 - p_0) / N_total )
sigma_squared = p_null * (1 - p_null)
sigma_n = np.sqrt(sigma_squared / N_total)
print(f"Desviación estándar de la media muestral (sigma_n): {sigma_n:.5f}")


# ----------------------------------------
# --- 2. CÁLCULO DEL ESTADÍSTICO DE PRUEBA Z ---

# Fórmula: Z = | S_n - mu_n | / sigma_n
Z_statistic = np.abs(S_n - mu_n) / sigma_n
print("-" * 40)
print(f"Estadístico Z calculado: {Z_statistic:.3f}")


# ----------------------------------------
# --- 3. CÁLCULO DEL P-VALOR (PRUEBA BILATERAL) ---

# P(Z > Z_statistic) se calcula con la función de supervivencia (sf) de la normal.
# El p-valor bilateral es 2 * P(Z > Z_statistic)
p_value = 2 * norm.sf(Z_statistic)

print("-" * 40)
print(f"P-valor (5 cifras significativas): {p_value:.5f}")

Total de aristas posibles (N_total): 10000
Media Muestral (S_n): 0.103
Media Poblacional (mu_n): 0.1
Desviación estándar de la media muestral (sigma_n): 0.00300
----------------------------------------
Estadístico Z calculado: 1.000
----------------------------------------
P-valor (5 cifras significativas): 0.31731


## Problem 9

In [1]:
import numpy as np

# Matriz de adyacencia (según la imagen)
A = np.array([[0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
	[1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
	[1, 1, 0, 0, 0, 1, 0, 1, 1, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
	[1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
	[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
	[0, 0, 0, 0, 1, 0, 1, 0, 1, 0]])

# Comunidades (0 o 1)
# tipo 1 -> comunidad 0, tipo 2 -> comunidad 1
communities = np.array([0,1,0,1,0,1,0,1,0,1])

# Grados
k = np.sum(A, axis=1)

# Número total de aristas
m = np.sum(k) / 2

# Cálculo de la modularidad
Q = 0
for i in range(len(A)):
    for j in range(len(A)):
        if communities[i] == communities[j]:  # misma comunidad
            Q += A[i,j] - (k[i]*k[j])/(2*m)

Q /= 2*m

print(f"Modularidad Q = {Q:.3f}")


Modularidad Q = -0.204


# Lecture 2

## Page 4: Eigen Vector Centrality

In [8]:
A = np.array([[1,0,0,0],
    [1,0,0,0],
    [1,0,0,0],
    [1,0,0,0]])

import networkx as nx

G = nx.from_numpy_array(A, create_using=nx.DiGraph)

# 3. Calcular la Centralidad de Autovector
# networkx.eigenvector_centrality calcula el autovector derecho, 
# el cual está relacionado con el grado de SALIDA.
centralidad = nx.eigenvector_centrality(G)

print("--- Centralidad de Autovector (Autovector DERECHO) ---")
# Mostrar resultados
for nodo, valor in sorted(centralidad.items()):
    print(f"Nodo {nodo+1}: {valor:.8f}")

--- Centralidad de Autovector (Autovector DERECHO) ---
Nodo 1: 1.00000000
Nodo 2: 0.00000095
Nodo 3: 0.00000095
Nodo 4: 0.00000095


In [9]:
A = np.array([[1,1,1,1],
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0]])

import networkx as nx

G = nx.from_numpy_array(A, create_using=nx.DiGraph)

# 3. Calcular la Centralidad de Autovector
# networkx.eigenvector_centrality calcula el autovector derecho, 
# el cual está relacionado con el grado de SALIDA.
centralidad = nx.eigenvector_centrality(G)

print("--- Centralidad de Autovector (Autovector DERECHO) ---")
# Mostrar resultados
for nodo, valor in sorted(centralidad.items()):
    print(f"Nodo {nodo+1}: {valor:.8f}")

--- Centralidad de Autovector (Autovector DERECHO) ---
Nodo 1: 0.50000000
Nodo 2: 0.50000000
Nodo 3: 0.50000000
Nodo 4: 0.50000000


In [10]:
A = np.array([[1,1,1,1],
    [1,0,0,0],
    [1,0,0,0],
    [1,0,0,0]])

import networkx as nx

G = nx.from_numpy_array(A, create_using=nx.DiGraph)

# 3. Calcular la Centralidad de Autovector
# networkx.eigenvector_centrality calcula el autovector derecho, 
# el cual está relacionado con el grado de SALIDA.
centralidad = nx.eigenvector_centrality(G)

print("--- Centralidad de Autovector (Autovector DERECHO) ---")
# Mostrar resultados
for nodo, valor in sorted(centralidad.items()):
    print(f"Nodo {nodo+1}: {valor:.8f}")

--- Centralidad de Autovector (Autovector DERECHO) ---
Nodo 1: 0.79917149
Nodo 2: 0.34704703
Nodo 3: 0.34704703
Nodo 4: 0.34704703


## Page 5: Katz Centrality

In [ ]:
import numpy as np

A = np.array([[0,1,1,1],
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0]])
A@A@A

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
import networkx as nx
import numpy as np

# Definir la matriz de adyacencia
A = np.array([
    [0, 1, 1, 1],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]
])

# Crear un grafo dirigido a partir de la matriz de adyacencia
G = nx.from_numpy_array(A, create_using=nx.DiGraph)

# Calcular la centralidad de Katz con los valores predeterminados
# de alpha=0.1 y beta=1.0. La función devuelve un diccionario.
# La normalización es por defecto a la norma L2.
katz_centrality = nx.katz_centrality(G, alpha=0.1, beta=1.0)

# Imprimir los resultados
print("Valores de Centralidad de Katz (sin redondear):")
for node, centrality in katz_centrality.items():
    print(f"Node {node}: {centrality:.6f}")
    
# Imprimir los resultados redondeados a 3 cifras significativas
print("\nValores de Centralidad de Katz (redondeados a 3 cifras significativas):")
for node, centrality in katz_centrality.items():
    print(f"Node {node}: {centrality:.3f}")

Valores de Centralidad de Katz (sin redondear):
Node 0: 0.464739
Node 1: 0.511213
Node 2: 0.511213
Node 3: 0.511213

Valores de Centralidad de Katz (redondeados a 3 cifras significativas):
Node 0: 0.465
Node 1: 0.511
Node 2: 0.511
Node 3: 0.511


## 6) 

In [ ]:
A = np.array([[0, 1, 1, 1, 1, 1, 1],
    [1, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 0, 0],
    [1, 0, 0, 1, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 1, 0]]
    )

# Crear un grafo dirigido a partir de la matriz de adyacencia
G = nx.from_numpy_array(A, create_using=nx.DiGraph)

# Calcular la centralidad de Katz con los valores predeterminados
# de alpha=0.1 y beta=1.0. La función devuelve un diccionario.
# La normalización es por defecto a la norma L2.
katz_centrality = nx.katz_centrality(G, alpha=0.1, beta=1.0)

# Imprimir los resultados
print("Valores de Centralidad de Katz (sin redondear):")
for node, centrality in katz_centrality.items():
    print(f"Node {node}: {centrality:.6f}")
    
# Imprimir los resultados redondeados a 3 cifras significativas
print("\nValores de Centralidad de Katz (redondeados a 3 cifras significativas):")
for node, centrality in katz_centrality.items():
    print(f"Node {node}: {centrality:.3f}")

Valores de Centralidad de Katz (sin redondear):
Node 0: 0.490292
Node 1: 0.362204
Node 2: 0.362204
Node 3: 0.362204
Node 4: 0.362204
Node 5: 0.358582
Node 6: 0.325984

Valores de Centralidad de Katz (redondeados a 3 cifras significativas):
Node 0: 0.490
Node 1: 0.362
Node 2: 0.362
Node 3: 0.362
Node 4: 0.362
Node 5: 0.359
Node 6: 0.326


In [31]:
import networkx as nx
import numpy as np

# Matriz de Adyacencia A del problema anterior
A = np.array([
    [0, 1, 1, 1, 1, 1, 1],
    [1, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 0, 0],
    [1, 0, 0, 1, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 1, 0]
])

# 1. Crear el grafo dirigido (DiGraph)
# PageRank opera sobre grafos dirigidos.
G = nx.from_numpy_array(A, create_using=nx.DiGraph)

# 2. Calcular la Centralidad de PageRank
# Usamos el valor por defecto alpha (α) = 0.85.
# El resto de los parámetros (como el vector de personalization) son los predeterminados.
# PageRank está normalizado por definición (la suma de las centralidades es 1).
pagerank_c = nx.pagerank(G, alpha=0.85)

# 3. Formatear la salida para tres cifras significativas
print("Centralidad de PageRank (α=0.85):")

# La función pagerank devuelve un diccionario: {nodo: valor_pagerank}
for node, centrality in pagerank_c.items():
    # Usamos el formato ':.3g' para asegurar la precisión de al menos 3 cifras significativas.
    formatted_centrality = f"{centrality:.3g}"
    print(f"Nodo {node}: {formatted_centrality}")

Centralidad de PageRank (α=0.85):
Nodo 0: 0.343
Nodo 1: 0.122
Nodo 2: 0.122
Nodo 3: 0.122
Nodo 4: 0.122
Nodo 5: 0.0998
Nodo 6: 0.07


In [33]:
import networkx as nx
import numpy as np

# Matriz de Adyacencia A
A = np.array([
    [0, 1, 1, 1, 1, 1, 1],
    [1, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 0, 0],
    [1, 0, 0, 1, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 1, 0]
])

# 1. Crear el grafo dirigido (DiGraph)
# HITS, como PageRank, opera sobre grafos dirigidos.
G = nx.from_numpy_array(A, create_using=nx.DiGraph)

# 2. Calcular la Centralidad HITS (Hubs y Authorities)
# La función networkx.hits devuelve una tupla de dos diccionarios: (hub_scores, authority_scores)
# La normalización (suma=1) está implícita en la implementación de networkx.
hub_scores, authority_scores = nx.hits(G)

# 3. Formatear la salida para tres cifras significativas

print("Centralidad de HITS (Hubs y Authorities):")
print("=========================================")


print("\nScores de Hubs (v):")
# Imprimir los Scores de Hubs (v)
for node in sorted(hub_scores.keys()):
    centrality = hub_scores[node]
    # Usamos el formato ':.3g' para asegurar la precisión de 3 cifras significativas.
    formatted_centrality = f"{centrality:.3g}"
    print(f"Nodo {node}: {formatted_centrality}")

# Imprimir los Scores de Authorities (w)
print("Scores de Authorities (w):")
for node in sorted(authority_scores.keys()):
    centrality = authority_scores[node]
    # Usamos el formato ':.3g' para asegurar la precisión de 3 cifras significativas.
    formatted_centrality = f"{centrality:.3g}"
    print(f"Nodo {node}: {formatted_centrality}")

Centralidad de HITS (Hubs y Authorities):

Scores de Hubs (v):
Nodo 0: 0.254
Nodo 1: 0.132
Nodo 2: 0.132
Nodo 3: 0.132
Nodo 4: 0.132
Nodo 5: 0.0868
Nodo 6: 0.132
Scores de Authorities (w):
Nodo 0: 0.254
Nodo 1: 0.132
Nodo 2: 0.132
Nodo 3: 0.132
Nodo 4: 0.132
Nodo 5: 0.132
Nodo 6: 0.0868


# Lecture 3

In [1]:
import numpy as np
import networkx as nx

# 1. Definir la Matriz de Distancias D (Corregida)
# Los nodos son {1, 2, 3, 4}.
# D[i, j] es la distancia entre el nodo i+1 y el nodo j+1.
D_matrix = np.array([
    [0, 3, 6, 5],
    [3, 0, 5, 6],
    [6, 5, 0, 3],
    [5, 6, 3, 0]
])

# 2. Crear un grafo de NetworkX a partir de la matriz
# Usamos un grafo completo (Complete Graph) donde las aristas son las distancias.
G = nx.from_numpy_array(D_matrix)

# NetworkX usa índices de 0 a 3 por defecto.
# Si queremos que los nodos se llamen 1, 2, 3, 4:
mapping = {i: i + 1 for i in G.nodes}
G = nx.relabel_nodes(G, mapping)


# 3. Encontrar el Árbol de Expansión Mínima (MST)
# 'weight' es el atributo por defecto que networkx usa para el peso.
mst_graph = nx.minimum_spanning_tree(G, algorithm='kruskal', weight='weight')

# 4. Calcular la suma de los pesos de las aristas del MST
mst_weight = mst_graph.size(weight='weight')

# 5. Imprimir el resultado

print(f"Aristas en el MST (Nodos: 1, 2, 3, 4): {mst_graph.edges.data()}")
print(f"La suma de todos los pesos de las aristas en el Árbol de Expansión Mínima es: {mst_weight}")

Aristas en el MST (Nodos: 1, 2, 3, 4): [(1, 2, {'weight': 3}), (1, 4, {'weight': 5}), (3, 4, {'weight': 3})]
La suma de todos los pesos de las aristas en el Árbol de Expansión Mínima es: 11.0


In [5]:
mst_graph

In [7]:
import networkx as nx
import numpy as np

# 1. Definir el grafo G a partir de la imagen
# El grafo tiene 8 nodos. Las aristas son:
# Ciclo: (1, 2), (2, 3), (3, 4), (4, 1)
# Camino: (3, 5), (5, 6), (6, 7), (7, 8)
G = nx.Graph()
G.add_edges_from([
    (1, 2), (2, 3), (3, 4), (4, 1), # Ciclo C4
    (3, 5), (5, 6), (6, 7), (7, 8)  # Camino P5 (conectado en 3)
])

# 2. Calcular el vector de Fiedler (vector propio de la Matriz Laplaciana)
# El fiedler_vector es el vector propio correspondiente al segundo valor propio más pequeño (lambda_2).
# networkx ya normaliza el vector tal que su norma euclidiana (norma L2) es 1.
try:
    fiedler_vector = nx.linalg.algebraicconnectivity.fiedler_vector(G)
except nx.NetworkXUnfeasible:
    # Este error podría ocurrir si el grafo no está conectado, pero este sí lo está.
    print("Error: El grafo no está conectado.")
    # El vector propio correspondiente a lambda_1 (el más pequeño) siempre es constante.
    # El vector propio correspondiente a lambda_2 (el segundo más pequeño) es el vector de Fiedler, 
    # y existe si el grafo no es trivial y tiene más de un componente conectado.
    
# 3. Formatear y redondear los resultados a tres cifras significativas
# networkx devuelve el vector en el orden del índice de los nodos: [1, 2, 3, 4, 5, 6, 7, 8]
rounded_vector = [round(val, 3) for val in fiedler_vector]

# 4. Imprimir los resultados
print("Vector de Fiedler (Vector Propio de lambda_2, normalizado a 1):")
for i, val in enumerate(rounded_vector):
    print(f"Node {i + 1}: {val}")

# 5. Para verificar la normalización (opcional)
norm_check = np.linalg.norm(fiedler_vector)
print(f"\nVerificación de la Norma L2 (debería ser 1.0): {norm_check:.5f}")

Vector de Fiedler (Vector Propio de lambda_2, normalizado a 1):
Node 1: -0.371
Node 2: -0.336
Node 3: -0.235
Node 4: -0.336
Node 5: 0.012
Node 6: 0.256
Node 7: 0.451
Node 8: 0.559

Verificación de la Norma L2 (debería ser 1.0): 1.00000


In [9]:
import networkx as nx
import numpy as np
from networkx.linalg.algebraicconnectivity import fiedler_vector

G = nx.Graph()
G.add_edges_from([
    (1,2),(2,3),(3,4),(4,1),
    (3,5),(5,6),(6,7),(7,8)
])

v = fiedler_vector(G, normalized=False)
v = np.array(v)
v = v / np.sqrt(np.sum(v**2))
print(np.round(v, 4))


[-0.3715 -0.3356 -0.235  -0.3356  0.0117  0.2561  0.451   0.5589]


# Lecture 4

In [2]:
m = 200*10**3
n = 10**6
p = 2*m/(n*(n-1))
p

4.000004000004e-07