# Functions for Numpy

1) Write a function called randomization that takes as input a positive integer n, and returns A, a random n x 1 Numpy array.

In [13]:
import random
import numpy as np
def randomization(n):
    """
    Arg:
      n - an integer
    Returns:
      A - a randomly-generated nx1 Numpy array.
    """
    num_list = []
    for x in range(n):
        num_list.append(random.randint(0,10))
    return np.array(num_list).reshape(n,1)

In [14]:
print(randomization(4))

[[10]
 [ 5]
 [ 2]
 [ 9]]


2. Write a function called operations that takes as input two positive integers h and w, makes two random matrices A and B, of size h x w, and returns A,B, and s, the sum of A and B.

In [7]:
import numpy as np

def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    A = np.random.rand(h,w)
    B = np.random.rand(h,w)
    return A,B,A+B
    #Your code here

In [8]:
print(operations(3,2))

(array([[0.39180464, 0.05567851],
       [0.28331059, 0.25259847],
       [0.30373144, 0.38455905]]), array([[0.62021652, 0.16976087],
       [0.17196353, 0.08122237],
       [0.06177084, 0.78631562]]), array([[1.01202117, 0.22543938],
       [0.45527412, 0.33382084],
       [0.36550228, 1.17087467]]))


3. Write a function called norm that takes as input two Numpy column arrays A and B, adds them, and returns s, the L2 norm of their sum.

In [10]:
def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
    #Your code here
    s = A+B
    return np.linalg.norm(s)
    raise NotImplementedError

In [11]:
a = np.random.rand(3)
b = np.random.rand(3)
print(norm(a,b))

1.1438783796358853


4. Neural Network

Here, we will write a function neural_network, which will apply a neural network operation with 2 inputs and 1 output and a given weight matrix.

In [20]:
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    #Your code here
    return np.tanh(inputs.T @ weights)
    raise NotImplementedError

In [21]:
input_variables = np.random.rand(2,1)
weights = np.random.rand(2,1)
print(neural_network(input_variables,weights))

[[0.63818459]]


5. Scalar function

Let's start with writing a scalar function scalar_function, which will apply the following operation with input x and y.

    If x <= y:
        return x*y
    else:
        return x/y

Note that x and y are scalars.

In [22]:
def scalar_function(x, y):
    """
    Returns the f(x,y) defined in the problem statement.
    """
    #Your code here
    if x <= y:
        return x*y
    else:
        return x/y
    raise NotImplementedError

In [23]:
print(scalar_function(4,3))

1.3333333333333333


6. Vector function

scalar_function can only handle scalar input, we could use the function np.vectorize() turn it into a vectorized function. Note that the input argument of np.vectorize() should be a scalar function, and the output of np.vectorize() is a new function that can handle vector input.

Please write a vector function vector_function, which will apply the operation  defined above element-wisely with input vectors with same dimension x and y.

In [24]:
def vector_function(x, y):
    """
    Make sure vector_function can deal with vector input x,y 
    """
    #Your code here
    vec_func = np.vectorize(scalar_function)
    return vec_func(x,y)
    raise NotImplementedError

In [25]:
print(vector_function([1,2,3],[5,3,6]))

[ 5  6 18]


7. In this problem, you are given a buggy piece of code and are asked to debug it.

The goal of this exercise is for you to set up a working debugging system for yourselves. (See the next page for an example.) Feel free to use other debuggers as you wish. But note that any extra print statement in submitted code will be graded as incorrect in the online code graders.

The function get_sum_metrics takes two arguments: a prediction and a list of metrics to apply to the prediction (say, for instance, the accuracy or the precision). Note that each metric is a function, not a number. The function should compute each of the metrics for the prediction and sum them. It should also add to this sum three default metrics, in this case, adding 0, 1 or 2 to the prediction.

original: 


def get_sum_metrics(predictions, metrics=[]):
    for i in range(3):
        metrics.append(lambda x: x + i)

    sum_metrics = 0
    for metric in metrics:
        sum_metrics += metric(predictions)

    return sum_metrics

In [30]:
def get_sum_metrics(predictions, metrics=None):
    if metrics is None:  # Fix: Prevent persistent default arguments
        metrics = []
    for i in range(3):
        metrics.append(lambda x, i=i: x + i)

    sum_metrics = 0
    for metric in metrics:
        sum_metrics += metric(predictions)

    return sum_metrics


In [29]:
# 🔹 Example usage:
predictions = 5
custom_metrics = [lambda x: x * 2, lambda x: x - 3]

print(get_sum_metrics(predictions, custom_metrics))

30
